# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.13.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.13.4/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/howllow/SharedWithUB/simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/howllow/SharedWithUB/simulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.13.4/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.13.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/howllow/SharedWithUB/simulator/CMakeFiles /Users/howllow/SharedWithUB/simulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/howllow/SharedWithUB/simulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Simulator

# Build rule for target.
Simulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Simulator
.PHONY : Simulator

# fast build rule for target.
Simulator/fast:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/build
.PHONY : Simulator/fast

MM.o: MM.cc.o

.PHONY : MM.o

# target to build an object file
MM.cc.o:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/MM.cc.o
.PHONY : MM.cc.o

MM.i: MM.cc.i

.PHONY : MM.i

# target to preprocess a source file
MM.cc.i:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/MM.cc.i
.PHONY : MM.cc.i

MM.s: MM.cc.s

.PHONY : MM.s

# target to generate assembly for a file
MM.cc.s:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/MM.cc.s
.PHONY : MM.cc.s

Simulator.o: Simulator.cc.o

.PHONY : Simulator.o

# target to build an object file
Simulator.cc.o:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/Simulator.cc.o
.PHONY : Simulator.cc.o

Simulator.i: Simulator.cc.i

.PHONY : Simulator.i

# target to preprocess a source file
Simulator.cc.i:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/Simulator.cc.i
.PHONY : Simulator.cc.i

Simulator.s: Simulator.cc.s

.PHONY : Simulator.s

# target to generate assembly for a file
Simulator.cc.s:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/Simulator.cc.s
.PHONY : Simulator.cc.s

decode.o: decode.cc.o

.PHONY : decode.o

# target to build an object file
decode.cc.o:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/decode.cc.o
.PHONY : decode.cc.o

decode.i: decode.cc.i

.PHONY : decode.i

# target to preprocess a source file
decode.cc.i:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/decode.cc.i
.PHONY : decode.cc.i

decode.s: decode.cc.s

.PHONY : decode.s

# target to generate assembly for a file
decode.cc.s:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/decode.cc.s
.PHONY : decode.cc.s

execute.o: execute.cc.o

.PHONY : execute.o

# target to build an object file
execute.cc.o:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/execute.cc.o
.PHONY : execute.cc.o

execute.i: execute.cc.i

.PHONY : execute.i

# target to preprocess a source file
execute.cc.i:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/execute.cc.i
.PHONY : execute.cc.i

execute.s: execute.cc.s

.PHONY : execute.s

# target to generate assembly for a file
execute.cc.s:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/execute.cc.s
.PHONY : execute.cc.s

fetch.o: fetch.cc.o

.PHONY : fetch.o

# target to build an object file
fetch.cc.o:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/fetch.cc.o
.PHONY : fetch.cc.o

fetch.i: fetch.cc.i

.PHONY : fetch.i

# target to preprocess a source file
fetch.cc.i:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/fetch.cc.i
.PHONY : fetch.cc.i

fetch.s: fetch.cc.s

.PHONY : fetch.s

# target to generate assembly for a file
fetch.cc.s:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/fetch.cc.s
.PHONY : fetch.cc.s

main.o: main.cc.o

.PHONY : main.o

# target to build an object file
main.cc.o:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/main.cc.o
.PHONY : main.cc.o

main.i: main.cc.i

.PHONY : main.i

# target to preprocess a source file
main.cc.i:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/main.cc.i
.PHONY : main.cc.i

main.s: main.cc.s

.PHONY : main.s

# target to generate assembly for a file
main.cc.s:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/main.cc.s
.PHONY : main.cc.s

memory.o: memory.cc.o

.PHONY : memory.o

# target to build an object file
memory.cc.o:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/memory.cc.o
.PHONY : memory.cc.o

memory.i: memory.cc.i

.PHONY : memory.i

# target to preprocess a source file
memory.cc.i:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/memory.cc.i
.PHONY : memory.cc.i

memory.s: memory.cc.s

.PHONY : memory.s

# target to generate assembly for a file
memory.cc.s:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/memory.cc.s
.PHONY : memory.cc.s

writeBack.o: writeBack.cc.o

.PHONY : writeBack.o

# target to build an object file
writeBack.cc.o:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/writeBack.cc.o
.PHONY : writeBack.cc.o

writeBack.i: writeBack.cc.i

.PHONY : writeBack.i

# target to preprocess a source file
writeBack.cc.i:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/writeBack.cc.i
.PHONY : writeBack.cc.i

writeBack.s: writeBack.cc.s

.PHONY : writeBack.s

# target to generate assembly for a file
writeBack.cc.s:
	$(MAKE) -f CMakeFiles/Simulator.dir/build.make CMakeFiles/Simulator.dir/writeBack.cc.s
.PHONY : writeBack.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Simulator"
	@echo "... MM.o"
	@echo "... MM.i"
	@echo "... MM.s"
	@echo "... Simulator.o"
	@echo "... Simulator.i"
	@echo "... Simulator.s"
	@echo "... decode.o"
	@echo "... decode.i"
	@echo "... decode.s"
	@echo "... execute.o"
	@echo "... execute.i"
	@echo "... execute.s"
	@echo "... fetch.o"
	@echo "... fetch.i"
	@echo "... fetch.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... writeBack.o"
	@echo "... writeBack.i"
	@echo "... writeBack.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

